package com.api.bizplay_conversational.service.rootAgentService;

import com.api.bizplay_conversational.model.request.BizplayPlanAgentRequest;
import com.api.bizplay_conversational.model.response.BizplayPlanAgentResponse;
import com.api.bizplay_conversational.model.response.TripPlanAgentResponse;
import com.api.bizplay_conversational.service.bizplayPlanAgentService.BizplayPlanAgentService;
import com.api.bizplay_conversational.service.bizplaySettlementAgentService.BizplaySettlementAgentService;
import com.api.bizplay_conversational.service.bookingDemoAgentService.BookingDemoAgentService;
import com.api.bizplay_conversational.service.slotFillerAgentService.SlotFillerAgentService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Root agent — see {@link RootAgentService}. Three responsibilities, nothing more:
 *
 * <ol>
 *   <li><b>Route.</b> Decide which specialist should take this turn.</li>
 *   <li><b>Remember.</b> Hold one child session per agent, so switching back and forth resumes
 *       where the user left off instead of starting over.</li>
 *   <li><b>Delegate.</b> Hand the turn over untouched and return the child's own answer.</li>
 * </ol>
 *
 * <p>Routing is decided by the LLM, not a keyword list: what a user means by "지난달 부산 출장 처리
 * 해줘" is a judgement, and a phrase table would be wrong for every phrasing nobody thought of.
 * The two deterministic cases are the ones that are genuinely facts rather than intent — a chip
 * token our own UI generated belongs to whichever agent generated it, and a turn that answers a
 * question the active agent just asked belongs to that agent.
 *
 * <p>Root routing state is in memory; the child sessions themselves persist exactly as they do
 * today, so a restart loses only which agent was active, not the work.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class RootAgentServiceImple implements RootAgentService {

    private final BizplayPlanAgentService bizplayPlanAgentService;
    private final BizplaySettlementAgentService bizplaySettlementAgentService;
    private final BookingDemoAgentService bookingDemoAgentService;
    private final SlotFillerAgentService slotFillerAgentService;
    private final ObjectMapper objectMapper;

    private static final String PLAN = "PLAN";
    private static final String SETTLEMENT = "SETTLEMENT";
    private static final String BOOKING = "BOOKING";

    /** rootSessionId -> {active, planSessionId, settlementSessionId, bookingSessionId}. */
    private final Map<String, ObjectNode> sessions = new ConcurrentHashMap<>();

    /**
     * Chip tokens, and which agent owns them. These are generated by our own UI and matched
     * verbatim by the child state machines, so routing them is a lookup, not a guess — and it
     * must never reach the LLM, which could read a bare token as something else entirely.
     */
    private static final Map<String, String> TOKEN_OWNER = Map.ofEntries(
            Map.entry("settle-plan:", SETTLEMENT), Map.entry("settle-start", SETTLEMENT),
            Map.entry("card-types:", SETTLEMENT), Map.entry("receipt:", SETTLEMENT),
            Map.entry("receipts-done", SETTLEMENT), Map.entry("evidence-period:", SETTLEMENT),
            Map.entry("manual-expense", SETTLEMENT), Map.entry("trankind:", SETTLEMENT),
            Map.entry("expense-confirm", SETTLEMENT), Map.entry("expense-cancel", SETTLEMENT),
            Map.entry("approver:", SETTLEMENT), Map.entry("pending-plans", SETTLEMENT),
            Map.entry("stop:", SETTLEMENT), Map.entry("submit", SETTLEMENT),
            Map.entry("offer:", BOOKING), Map.entry("booking-confirm", BOOKING),
            Map.entry("booking-cancel", BOOKING),
            Map.entry("trip type:", PLAN), Map.entry("purpose:", PLAN), Map.entry("traveler:", PLAN));

    @Override
    public BizplayPlanAgentResponse chat(BizplayPlanAgentRequest request, String bizplayToken) {
        String message = request.getMessage() == null ? "" : request.getMessage().trim();
        boolean ko = hasHangul(message);
        String rootId = request.getSessionId() == null || request.getSessionId().isBlank()
                ? UUID.randomUUID().toString()
                : request.getSessionId();
        ObjectNode state = sessions.computeIfAbsent(rootId, k -> objectMapper.createObjectNode());

        String target = route(state, message, ko);
        if (target == null) {
            return askWhichAgent(rootId, ko);
        }
        state.put("active", target);

        // The child keeps its OWN session. The root id never reaches it, and its id never reaches
        // the caller - otherwise the next turn would bypass the router entirely.
        String childSessionId = state.path(sessionKey(target)).asText(null);
        // Confirming a booking exists only on the booking agent's create path, so a chat turn
        // carrying that token would fall through and re-offer the same list. In a one-chat design
        // the router bridges it: the user should not have to know which call finishes the job.
        if (BOOKING.equals(target) && message.toLowerCase(Locale.ROOT).startsWith("booking-confirm")
                && childSessionId != null && !childSessionId.isBlank()) {
            return withRootSession(bookingDemoAgentService.confirm(childSessionId), rootId, target);
        }
        BizplayPlanAgentRequest child = childRequest(request, childSessionId);
        BizplayPlanAgentResponse answer = switch (target) {
            case SETTLEMENT -> bizplaySettlementAgentService.chat(child, bizplayToken);
            case BOOKING -> bookingDemoAgentService.chat(child);
            default -> bizplayPlanAgentService.chat(child, bizplayToken);
        };
        if (answer != null && answer.getSessionId() != null) {
            state.put(sessionKey(target), answer.getSessionId());
        }
        // The question the child just asked is what tells the router, next turn, whether the user
        // is ANSWERING or switching tasks. Without it "출장자는 김충북이야" - a traveller name given
        // to the plan agent - was read as a settlement request purely because it contains 출장자.
        if (answer != null && answer.getReply() != null) {
            state.put("lastAsk", answer.getReply());
        }
        state.put("awaitingValue", awaitingValue(answer));
        log.info("Root agent routed a turn to {} (root session {}).", target, rootId);
        return withRootSession(answer, rootId, target);
    }

    @Override
    public BizplayPlanAgentResponse create(String sessionId, String corpNo, String bizplayToken,
                                           JsonNode approvalLines) {
        ObjectNode state = sessions.get(sessionId);
        if (state == null || !state.hasNonNull("active")) {
            throw new IllegalArgumentException("Nothing in progress on this conversation yet.");
        }
        String target = state.path("active").asText();
        String childId = state.path(sessionKey(target)).asText(null);
        if (childId == null || childId.isBlank()) {
            throw new IllegalArgumentException("The " + target.toLowerCase(Locale.ROOT)
                    + " conversation has not started yet.");
        }
        BizplayPlanAgentResponse answer = switch (target) {
            case SETTLEMENT -> bizplaySettlementAgentService.createSettlement(childId, corpNo,
                    bizplayToken, approvalLines);
            case BOOKING -> bookingDemoAgentService.confirm(childId);
            default -> bizplayPlanAgentService.createPlan(childId, corpNo, bizplayToken, approvalLines);
        };
        log.info("Root agent completed the {} flow (root session {}).", target, sessionId);
        return withRootSession(answer, sessionId, target);
    }

    // --- routing -----------------------------------------------------------------

    /** The agent that should take this turn, or null when it is genuinely unclear. */
    private String route(ObjectNode state, String message, boolean ko) {
        String active = state.path("active").asText(null);
        String lower = message.toLowerCase(Locale.ROOT);

        // 1. A chip token belongs to whoever issued it. Not intent - provenance.
        for (Map.Entry<String, String> e : TOKEN_OWNER.entrySet()) {
            if (lower.startsWith(e.getKey())) {
                return e.getValue();
            }
        }
        // 2. Nothing running yet: the message has to say what the user wants.
        if (active == null) {
            return classify(message, ko, false, "");
        }
        // 3. The active agent asked for a VALUE and has not got it yet. Whatever comes back is
        //    that value, so the router must not touch it - the classifier read the traveller name
        //    "출장자는 김충북이야" as a settlement request purely because it contains 출장자, which
        //    abandoned a half-built plan. This is the child's own declared state, not a guess about
        //    wording, and it deliberately does NOT fire for a list of choices: "예약도 하고 싶어"
        //    while a plan list is on screen is a real switch, and still routes as one.
        if (state.path("awaitingValue").asBoolean(false)) {
            return active;
        }
        // 4. The agent offered a LIST rather than asking for a value, which is exactly where people
        //    change their mind ("정산 계속할게" while looking at booking offers). The cautious
        //    mid-flow wording existed to protect the case rule 3 now handles deterministically, and
        //    it made switching back nearly impossible - so classify this the same way a fresh
        //    conversation is classified, and fall back to the current task when nothing is named.
        String named = classify(message, ko, false, state.path("lastAsk").asText(""));
        return named == null ? active : named;
    }

    /**
     * Ask the LLM which assistant the message is asking for. Returns null when it says none
     * clearly applies - which is the honest answer for "오사카" or "네", and for a first message
     * that could mean anything.
     *
     * @param mustBeExplicit true mid-flow, where silence means "carry on" rather than "unclear"
     */
    private String classify(String message, boolean ko, boolean mustBeExplicit, String lastAsk) {
        if (message.isBlank()) {
            return null;
        }
        // Vocabulary, not a phrase table: the model still judges the sentence, but a 14B classifier
        // needs to know that 정산/영수증/경비 point one way and 예약/티켓/숙소 the other. Without
        // these cues a terse "정산 계속할게" came back unclassified and the conversation sat where
        // it was, looking stuck.
        String meaning = "which assistant this message is asking for, as EXACTLY one of: "
                + "PLAN - writing or drafting a business-trip REQUEST before the trip "
                + "(출장계획서, 계획, 신청, 기안, plan, request); "
                + "SETTLEMENT - settling a trip already taken, its expenses and receipts "
                + "(출장정산서, 정산, 영수증, 경비, 증빙, settle, expense, receipt); "
                + "BOOKING - reserving transport or a place to stay "
                + "(예약, 티켓, 항공, 기차, 숙소, 호텔, book, reserve, flight, hotel). "
                + (mustBeExplicit
                    ? "The user is already mid-task and was JUST ASKED: \"" + shorten(lastAsk) + "\" "
                      + "If this message could be an ANSWER to that question, omit the field - even "
                      + "when it mentions travel words. Answer only when they are plainly starting a "
                      + "DIFFERENT one of the three tasks."
                    : "Omit the field entirely if the message does not clearly indicate one of them.");
        try {
            JsonNode got = slotFillerAgentService.extract(message, Map.of("agent", meaning), ko);
            String v = got.path("agent").asText("").trim().toUpperCase(Locale.ROOT);
            if (PLAN.equals(v) || SETTLEMENT.equals(v) || BOOKING.equals(v)) {
                return v;
            }
        } catch (Exception e) {
            log.warn("Root routing classification failed ({}); leaving the turn unrouted.", e.getMessage());
        }
        return null;
    }

    /**
     * Is the child waiting for a VALUE (as opposed to a choice, or nothing)? Two signals, both
     * the agent describing itself: an outstanding required form field, or a slot question.
     * A pendingChoices list does NOT count - offering options leaves the user free to change
     * their mind about the whole task.
     */
    private boolean awaitingValue(BizplayPlanAgentResponse a) {
        if (a == null) {
            return false;
        }
        if (a.getMissingFields() != null && !a.getMissingFields().isEmpty()) {
            return true;
        }
        String intent = a.getIntent() == null ? "" : a.getIntent();
        // FORM_LOAD and FIELD_COMPLETION are the plan agent collecting form values. They ask for
        // fields in prose and report no missingFields, so without naming them here a reply like
        // "오사카, 인천에서 출발, 10월 5일부터 7일까지, 출장자는 김충북" was read as a settlement
        // request - the words are all trip words - and a half-built plan was abandoned mid-answer.
        return intent.endsWith("_SLOT_FILLING") || intent.endsWith("_SLOT_PENDING")
                || "FORM_LOAD".equals(intent) || "FIELD_COMPLETION".equals(intent);
    }

    /** The tail of the question, kept short so it guides the router without dominating it. */
    private String shorten(String ask) {
        String a = ask == null ? "" : ask.replaceAll("\s+", " ").trim();
        return a.length() <= 160 ? a : a.substring(a.length() - 160);
    }

    /** No active flow and nothing clear in the message: ask, rather than pick one and be wrong. */
    private BizplayPlanAgentResponse askWhichAgent(String rootId, boolean ko) {
        List<TripPlanAgentResponse.Option> options = List.of(
                option(t(ko, "Plan a trip", "출장 계획 작성"), t(ko, "I want to plan a business trip.",
                        "출장 계획을 작성하고 싶어요.")),
                option(t(ko, "Settle expenses", "출장 정산"), t(ko, "I want to settle a finished trip.",
                        "다녀온 출장을 정산하고 싶어요.")),
                option(t(ko, "Book travel", "출장 예약"), t(ko, "I want to book transport or a hotel.",
                        "교통편이나 숙소를 예약하고 싶어요.")));
        return BizplayPlanAgentResponse.builder()
                .sessionId(rootId)
                .intent("ROOT_AGENT_SELECTION")
                .subAgents(List.of("ROOT_AGENT"))
                .reply(t(ko, "Would you like to plan a trip, settle one you have finished, or book "
                                + "transport and a hotel?",
                        "출장 계획을 세우실까요, 다녀온 출장을 정산하실까요, 아니면 교통편·숙소를 예약하실까요?"))
                .pendingChoices(List.of(TripPlanAgentResponse.PendingChoice.builder()
                        .kind("ROOT_AGENT")
                        .name(t(ko, "what would you like to do?", "무엇을 도와드릴까요?"))
                        .options(options)
                        .build()))
                .build();
    }

    // --- plumbing ----------------------------------------------------------------

    private TripPlanAgentResponse.Option option(String label, String sendText) {
        return TripPlanAgentResponse.Option.builder().label(label).sendText(sendText).build();
    }

    private String sessionKey(String target) {
        return target.toLowerCase(Locale.ROOT) + "SessionId";
    }

    /** The same turn, aimed at a child agent and carrying that child's own session id. */
    private BizplayPlanAgentRequest childRequest(BizplayPlanAgentRequest source, String childSessionId) {
        BizplayPlanAgentRequest r = new BizplayPlanAgentRequest();
        r.setCorpNo(source.getCorpNo());
        r.setCorpUserId(source.getCorpUserId());
        r.setCorporationId(source.getCorporationId());
        r.setMessage(source.getMessage());
        r.setFileIds(source.getFileIds());
        r.setTravelerCorpUserIds(source.getTravelerCorpUserIds());
        r.setBstrPlanApprovalId(source.getBstrPlanApprovalId());
        r.setSessionId(childSessionId);
        return r;
    }

    /**
     * The child's answer, with the ROOT session id in place of its own and a note of who handled
     * it. Everything else is passed through untouched — the whole point is that the specialists
     * answer for themselves.
     */
    private BizplayPlanAgentResponse withRootSession(BizplayPlanAgentResponse a, String rootId,
                                                     String target) {
        if (a == null) {
            return null;
        }
        List<String> agents = new ArrayList<>();
        agents.add("ROOT_AGENT");
        agents.add(target + "_AGENT");
        if (a.getSubAgents() != null) {
            agents.addAll(a.getSubAgents());
        }
        return BizplayPlanAgentResponse.builder()
                .sessionId(rootId)
                .status(a.getStatus())
                .intent(a.getIntent())
                .subAgents(agents)
                .reply(a.getReply())
                .pendingChoices(a.getPendingChoices())
                .missingFields(a.getMissingFields())
                .travelers(a.getTravelers())
                .travelerIds(a.getTravelerIds())
                .destination(a.getDestination())
                .origin(a.getOrigin())
                .draftJson(a.getDraftJson())
                .createdDate(a.getCreatedDate())
                .updatedDate(a.getUpdatedDate())
                .build();
    }

    private boolean hasHangul(String s) {
        return s != null && s.codePoints().anyMatch(c -> c >= 0xAC00 && c <= 0xD7A3);
    }

    private String t(boolean ko, String en, String korean) {
        return ko ? korean : en;
    }
}
